version: '3'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - type: bind
        source: database-setup.sql
        target: /docker-entrypoint-initdb.d/database-setup.sql

  api-server:
    image: python:3.10
    entrypoint: ["sleep", "infinity"]
    working_dir: /src
    environment:
      DB_USERNAME: "flask"
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - type: bind
        source: .
        target: /src
